### PR TITLE
added raGrantedDate to projects

### PR DESCRIPTION
**Pull request by joefitter**

### CODE REVIEW

**Comment by lennym** [comment]
Is there a reason this is a property on the project and not on the RA?

**Comment by joefitter** [comment]
we have raDueDate on the project, and it's only shown in the context of the project

**Comment by joefitter** [comment]
else for a project we'd need to get the ra's, find the latest granted, then get the date

**Comment by lennym** [comment]
Makes sense. I forget these work just like project versions.

**Pull request merged**
