### PR TITLE
Add unscoped functions for fetching profiles

### PR DESCRIPTION
**Pull request by wheelsandcogs**
Instead of allowing the standard query functions to optionally include establishment scoping, we have decided to have separate functions that must be explicitly called in order to get an unscoped query across all establishments.

This will help prevent mistakes that could lead to exposing more data than we want to.

### CODE REVIEW

**Comment by lennym** [comment]
This seems like a lot of extra code for something that's only going to be used on one endpoint.

Do we _need_ to add more methods to the schema to do this?

**Comment by wheelsandcogs** [comment]
We can remove the code around roles if the people search results aren't going to show them (ticket says just "name, date of birth and any establishment affiliations" for now), but the designs for the people search have the roles column?

If we want to keep the standard datatable features like pagination, sorting, etc but don't want to modify the existing functions to have optional scoping, then it just made sense to duplicate the existing functions and remove the scoping rather than trying to reinvent something new.

**Comment by lennym** [comment]
My point was more that these _shouldn't_ be new methods on the global schema models, but should be implemented by direct query manipulation in the endpoint itself.

This way we load a lot of extra functions on _all_ models to do a thing we know we only do once.

**Comment by wheelsandcogs** [comment]
Moving to api.

**Pull request closed without merging**
