### PR TITLE
version ordering of Amend in prog project results in an impossible si…

### PR DESCRIPTION
**Pull request by joefitter**
…tuation - granted most recent, but amend in progress

### CODE REVIEW

**Comment by lennym** [comment]
When these are looked up in the code they're ordered by dates, so I'd probably set explicit dates if we want explicit ordering.

**Comment by joefitter** [comment]
they are added in reverse, with a delay in between each for that reason

**Comment by joefitter** [comment]
these were just added backwards

**Comment by lennym** [comment]
Nah, I think that's coincidence. Give them explicit dates.

All it takes is someone to replace the sequential ordering with a `Promise.all` (which is how it was until I recently made it sequential to make debugging possible) and it'll sporadically fall over.

**Comment by joefitter** [comment]
I'm probably thinking of a different table then, as one of the ones I wrote _was_ sequential 🤷‍♂

added dates to them

**Pull request merged**
