### PR TITLE
Rename trainingModules table with snake_case

### PR DESCRIPTION
**Pull request by wheelsandcogs**

### CODE REVIEW

**Comment by lennym** [comment]
Does this also need to be updated, or is it still ok?

https://github.com/UKHomeOffice/asl-schema/blob/master/schema/profile.js#L64

**Comment by lennym** [comment]
I'm hoping it's fine, because otherwise this might be leaky as hell if it potentially needs to be changed everywhere we do joins in implementation.

**Comment by wheelsandcogs** [comment]
I think in that instance it's the relation name, not the table name, so it should match whatever is used here: https://github.com/UKHomeOffice/asl-schema/blob/bugfix/training-module-table-name/schema/profile.js#L210

**Comment by wheelsandcogs** [comment]
The migrations and seeding seem to be working correctly so I assume it's ok.

**Pull request merged**
